### ISSUE TITLE
crash when opening bispectral.exr in Windows 

### ISSUE THREAD

**Issue by irinaciortan** [afichet/spectral-exr#2]
Hi,

I tried to open the bispectral.exr on Windows 10, but most of the times the viewer crashes. I managed to open it only twice, but I wouldn't know why sometimes it opened, other times it didn't.

**Comment by afichet** [comment]
Hi,

There is no viewer in this repository, so I am not sure which program you are referring to.
Could you give me more details?

Cheers.

**Comment by irinaciortan** [comment]
Oh, sorry! I was referring to the Spectral Viewer. I got here from links found in the video on this page: https://cgg.mff.cuni.cz/publications/an-openexr-layout-for-spectral-images/
I thought this is the repository for the viewer as well...

**Comment by afichet** [comment]
I see.
I don't expect the software to work reliably on fluorescent dataset right now. It is highly experimental and ultra slow.
But, you can file an issue on the Spectral Viewer repository there: https://gitlab.com/mrf-devteam/spectral-viewer
